### PR TITLE
Improved PNG compression.

### PR DESCRIPTION
**Pull request by rockymadden**
Part of my "save the bits" initiative ;)

### CODE REVIEW

**Comment by atlemo** [comment]
I already use ImageOptim lossless PNG compression. How did you manage to compress it even more?

**Comment by rockymadden** [comment]
OptiPNG, many were 20+ percent.

**Comment by venam** [comment]
I feel like there's loss of colors in the "optimized" tiles.
Is it just me ? They kind of feel different.

**Comment by rockymadden** [comment]
Is there one in particular? I'd be happy to look into it.

**Comment by macik** [comment]
I am interested in graphic optimization to. 
So take a look at  https://github.com/subtlepatterns/SubtlePatterns/pull/19

**Pull request closed without merging**
